version: "3.8"

services:
  db:
    container_name: lokmart_postgres_db
    build:
      context: deploy/postgresql
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - .env
    restart: always

  backend:
    container_name: lokmart_backend
    build:
      context: .
      dockerfile: deploy/backend/Dockerfile
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    env_file:
      - .env
    command: make start-docker
    restart: always
    depends_on:
      - db

  redis:
    image: redis:alpine

  celery:
    container_name: lokmart_celery
    build:
      context: .
      dockerfile: deploy/backend/Dockerfile
    command: make worker
    env_file:
      - .env
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - db
      - backend
      - redis
    restart: always

  nginx:
    container_name: lokmart_nginx
    build:
      context: deploy/nginx
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8111:80"
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    restart: on-failure
    depends_on:
      - backend


volumes:
  postgres_data:
  static_volume:
  media_volume: