# Generated by Django 5.0.4 on 2024-05-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(default=0)),
                ('max_uses_user', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('start_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
            },
        ),
        migrations.CreateModel(
            name='ProductPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='products.product')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promo_codes', to='promocodes.promocode')),
            ],
            options={
                'verbose_name': 'product promo code',
                'verbose_name_plural': 'product promo codes',
            },
        ),
        migrations.CreateModel(
            name='UserUsesPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='promocodes.promocode')),
            ],
            options={
                'verbose_name': 'user uses promo code',
                'verbose_name_plural': 'user uses promo codes',
            },
        ),
    ]
