# Generated by Django 5.0.4 on 2024-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('private_key', models.CharField(max_length=256)),
                ('public_key', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Error', 'Error'), ('Failure', 'Failure')])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card')], default='CARD')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
    ]
